import React, { useEffect, useState } from 'react';
import { useDataContext } from '../contexts/DataContext';
import { deleteDocument } from '../services/firebaseService';
import { TABLE_NAMES } from '../constants';
import { useAppContext } from '../contexts/AppContext';

const SeedNurys: React.FC = () => {
    const { loans, archivedLoans } = useDataContext();
    const { showToast } = useAppContext();
    const [done, setDone] = useState(false);

    useEffect(() => {
        if (done) return;

        const cleanup = async () => {
            try {
                const allLoans = [...loans, ...archivedLoans];
                // Find all fictitious loans generated by the seeder
                const fictitiousLoans = allLoans.filter(l => 
                    l.clientName === 'Nurys Tolentino' && 
                    l.amount === 800 && 
                    l.notes === 'Cliente con buen puntaje de confianza. Liquidado exitosamente.'
                );

                if (fictitiousLoans.length > 0) {
                    console.log(`Found ${fictitiousLoans.length} fictitious loans for Nurys Tolentino. Deleting...`);
                    for (const loan of fictitiousLoans) {
                        await deleteDocument(TABLE_NAMES.LOANS, loan.id);
                    }
                    showToast(`Se eliminaron ${fictitiousLoans.length} préstamos ficticios duplicados de Nurys Tolentino para corregir la contabilidad.`, 'success');
                }
                setDone(true);
            } catch (e) {
                console.error("Error during fictitious loans cleanup:", e);
            }
        };

        // Only run cleanup if we have finished loading data
        if (loans.length > 0 || archivedLoans.length > 0) {
            cleanup();
        }
    }, [loans, archivedLoans, done, showToast]);

    return null;
};

export default SeedNurys;
